version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: tabulador
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./mongodb-data:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped

  mongo-express:
    image: mongo-express
    restart: always
    depends_on: 
    - "mongodb"
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/